apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ghostidp.fullname" . }}
  labels:
    {{- include "ghostidp.labels" . | nindent 4 }}
data:
  users.yaml: |
    {{ .Values.ghostidp.usersConfig | nindent 4 }}



