{{- with .Values.ghostidp.defaultOAuth2Client -}}
{{- if and .enabled (not .credentials.hydraGenerated) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-secret
data:
  CLIENT_ID: {{ .credentials.clientID | b64enc }}
  CLIENT_SECRET: {{ .credentials.clientSecret | b64enc }}
{{- end -}}
{{- end -}}