{{- with .Values.httpRoute -}}
{{- if .enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "ghostidp.fullname" $ }}-https
  labels:
    {{- include "ghostidp.labels" $ | nindent 4 }}
spec:
  parentRefs:
    - kind: Gateway
      name: {{ .gatewayName }}
      namespace: {{ .gatewayNamespace }}
  hostnames:
    {{- range uniq .hostnames }}
    - {{ . | quote }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /login
        - path:
            type: PathPrefix
            value: /consent
        - path:
            type: PathPrefix
            value: /logout
        - path:
            type: PathPrefix
            value: /assets
      backendRefs:
        - name: {{ include "ghostidp.fullname" $ }}
          port: {{ $.Values.service.port }}
      # When running locally, the gateway (nginx gateway fabric) does not
      # seem to add this header automatically on HTTPS routes, so we do it manually
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: "X-Forwarded-Proto"
                value: "https"
    - backendRefs:
        - name: ghostidp-hydra-public
          port: {{ $.Values.hydra.service.public.port }}
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: "X-Forwarded-Proto"
                value: "https"
{{- end -}}
{{- end -}}