# This is an example config
users:
  - username: alice
    display:
      description: An admin user
    email: alice@example.com
    given_name: Alice
    family_name: Smith
    custom_claims:
      roles:
        - admin
      department: engineering
      employee_id: "12345"

  - username: bob
    display:
      description: A regular user
    email: bob@example.com
    given_name: Bob
    family_name: Johnson
    custom_claims:
      roles:
        - user
      department: marketing
      employee_id: "67890"
