ghostidp:
  debug: true
  usersConfig: |
    users:
      - username: alice
        description: A demo user.
        email: alice@example.com
        given_name: Alice
        family_name: Smith
        custom_claims:
          department: engineering
          employed_id: 12345
          roles:
            - admin
            - user
      - username: bob
        description: A demo user.
        email: bob@example.com
        given_name: Bob
        family_name: Marvel
        custom_claims:
          department: engineering
          employed_id: 6587
          roles:
            - user

  defaultOAuth2Client:
    enabled: true
    name: default-oauth2-client
    clientName: "Default Client"
    skipConsent: false
    grantTypes:
      - client_credentials
      - implicit
      - authorization_code
      - refresh_token
    responseTypes:
      - id_token
      - code
    scope: "offline openid"
    credentials:
      hydraGenerated: false
      clientID: "my-default-client"
      clientSecret: "very-insecure-secret"
    redirectUris:
      - "http://127.0.0.1:5050/callback"
    postLogoutRedirectUris:
      - "http://127.0.0.1:5050/"
    tokenEndpointAuthMethod: client_secret_basic

# HTTP Route
httpRoute:
  enabled: true
  gatewayName: gateway
  gatewayNamespace: default
  hostnames:
    - idp.dev.local

#######################
# DEPENDENCIES VALUES #
#######################
hydra:
  fullnameOverride: ""
  serve:
    cookies:
      same_site_mode: Lax
  hydra:
    config:
      dsn: "memory"
      urls:
        self:
          public: "https://idp.dev.local"
          issuer: "https://idp.dev.local"         # Will target ghostidp-hydra-public:4444
        login: "https://idp.dev.local/login"      # Will target ghostidp:8080
        consent: "https://idp.dev.local/consent"  # Will target ghostidp:8080
        logout: "https://idp.dev.local/logout"    # Will target ghostidp:8080
  maester:
    enabled: false # set to true if you want to automatically create a default client in Hydra
  hydra-maester:
    image:
      # https://github.com/ory/hydra-maester/pull/159
      repository: localhost:5005/controller
      tag: latest
